# vim:ft=kitty
## name: Cloudberry Blackwater
## license: MIT
## blurb: Cloudberry tint of Blackwater: dark, neutrals leaned toward cloudberry (base #261207).

foreground #f3e1d8
background #261207
selection_foreground #f3e1d8
selection_background #4d2523
cursor #feafd4
cursor_text_color #1a0802
url_color #86c0cc
active_border_color #ba4889
inactive_border_color #8f786c
bell_border_color #e8c98a
wayland_titlebar_color #1f0d04
macos_titlebar_color #1f0d04
active_tab_foreground #1a0802
active_tab_background #fc8944
inactive_tab_foreground #cab8ae
inactive_tab_background #1f0d04
tab_bar_background #1a0802
mark1_foreground #1a0802
mark1_background #baa8dc
mark2_foreground #1a0802
mark2_background #ddb0ec
mark3_foreground #1a0802
mark3_background #7fb4e0

color0 #3c2416
color8 #4b2f20
color1 #f06a6a
color9 #ed5858
color2 #a3daa3
color10 #87cf8e
color3 #e8c98a
color11 #dcbb6d
color4 #8fb0f2
color12 #7da4f4
color5 #fd7ca5
color13 #fc6796
color6 #9ed0c4
color14 #7cc7b8
color7 #cab8ae
color15 #ddcbc2
color16 #f7ab84
color17 #e7c5d8
