# vim:ft=kitty
## name: Cloudberry Mire
## license: MIT
## blurb: Cloudberry tint of Mire: dark, neutrals leaned toward cloudberry (base #341e13).

foreground #f5e3da
background #341e13
selection_foreground #f5e3da
selection_background #582f2d
cursor #feafd4
cursor_text_color #251106
url_color #86c0cc
active_border_color #be4c8d
inactive_border_color #988276
bell_border_color #e8c98a
wayland_titlebar_color #2c160a
macos_titlebar_color #2c160a
active_tab_foreground #251106
active_tab_background #fc8944
inactive_tab_foreground #cfbdb3
inactive_tab_background #2c160a
tab_bar_background #251106
mark1_foreground #251106
mark1_background #baa8dc
mark2_foreground #251106
mark2_background #ddb0ec
mark3_foreground #251106
mark3_background #7fb4e0

color0 #462b1d
color8 #553524
color1 #f06a6a
color9 #ed5858
color2 #a3daa3
color10 #87cf8e
color3 #e8c98a
color11 #dcbb6d
color4 #8fb0f2
color12 #7da4f4
color5 #fd7ca5
color13 #fc6796
color6 #9ed0c4
color14 #7cc7b8
color7 #cfbdb3
color15 #e2d0c7
color16 #f7ab84
color17 #e7c5d8
