# vim:ft=kitty
## name: Cloudberry Fen
## license: MIT
## blurb: Cloudberry tint of Fen: dark, neutrals leaned toward cloudberry (base #553524).

foreground #f8e6dd
background #553524
selection_foreground #f8e6dd
selection_background #73463e
cursor #ffc4dd
cursor_text_color #3d2315
url_color #83d4db
active_border_color #dc67a7
inactive_border_color #a58575
bell_border_color #f0d6a0
wayland_titlebar_color #472b1c
macos_titlebar_color #472b1c
active_tab_foreground #3d2315
active_tab_background #f9a374
inactive_tab_foreground #cfbbb1
inactive_tab_background #472b1c
tab_bar_background #3d2315
mark1_foreground #3d2315
mark1_background #c9b0e8
mark2_foreground #3d2315
mark2_background #edbbfe
mark3_foreground #3d2315
mark3_background #9cc6ea

color0 #73513f
color8 #825f4d
color1 #fd8c85
color9 #fa7a71
color2 #bbe5b3
color10 #a1d99c
color3 #f0d6a0
color11 #e3c782
color4 #a4c3f6
color12 #8fb6f7
color5 #fe96b4
color13 #fd82a5
color6 #afdfdb
color14 #8bd5d1
color7 #cfbbb1
color15 #e3cfc5
color16 #fbc3a2
color17 #ecaed2
