{
  "metadata": {
    "copyright": [
      "SPDX-FileCopyrightText: Darkberry"
    ],
    "license": "SPDX-License-Identifier: MIT",
    "revision": 1,
    "name": "Crowberry Wisp"
  },
  "text-styles": {
    "Normal": {
      "text-color": "#403654",
      "selected-text-color": "#403654"
    },
    "Keyword": {
      "text-color": "#bf0b64",
      "selected-text-color": "#bf0b64",
      "bold": true
    },
    "Function": {
      "text-color": "#a63676",
      "selected-text-color": "#a63676"
    },
    "Variable": {
      "text-color": "#934b66",
      "selected-text-color": "#934b66"
    },
    "ControlFlow": {
      "text-color": "#bf0b64",
      "selected-text-color": "#bf0b64",
      "bold": true
    },
    "Operator": {
      "text-color": "#534967",
      "selected-text-color": "#534967"
    },
    "BuiltIn": {
      "text-color": "#6e52ab",
      "selected-text-color": "#6e52ab"
    },
    "Extension": {
      "text-color": "#a63676",
      "selected-text-color": "#a63676"
    },
    "Preprocessor": {
      "text-color": "#6e52ab",
      "selected-text-color": "#6e52ab"
    },
    "Attribute": {
      "text-color": "#3d5a8a",
      "selected-text-color": "#3d5a8a"
    },
    "Char": {
      "text-color": "#2c6f2d",
      "selected-text-color": "#2c6f2d"
    },
    "SpecialChar": {
      "text-color": "#006f5f",
      "selected-text-color": "#006f5f"
    },
    "String": {
      "text-color": "#2c6f2d",
      "selected-text-color": "#2c6f2d"
    },
    "VerbatimString": {
      "text-color": "#2c6f2d",
      "selected-text-color": "#2c6f2d"
    },
    "SpecialString": {
      "text-color": "#006f5f",
      "selected-text-color": "#006f5f"
    },
    "Import": {
      "text-color": "#6e52ab",
      "selected-text-color": "#6e52ab"
    },
    "DataType": {
      "text-color": "#8c3eb2",
      "selected-text-color": "#8c3eb2"
    },
    "DecVal": {
      "text-color": "#815b02",
      "selected-text-color": "#815b02"
    },
    "BaseN": {
      "text-color": "#815b02",
      "selected-text-color": "#815b02"
    },
    "Float": {
      "text-color": "#815b02",
      "selected-text-color": "#815b02"
    },
    "Constant": {
      "text-color": "#3659ca",
      "selected-text-color": "#3659ca"
    },
    "Comment": {
      "text-color": "#675f79",
      "selected-text-color": "#675f79",
      "italic": true
    },
    "Documentation": {
      "text-color": "#675f79",
      "selected-text-color": "#675f79",
      "italic": true
    },
    "Annotation": {
      "text-color": "#3d5a8a",
      "selected-text-color": "#3d5a8a"
    },
    "CommentVar": {
      "text-color": "#934b66",
      "selected-text-color": "#934b66"
    },
    "RegionMarker": {
      "text-color": "#6e52ab",
      "selected-text-color": "#6e52ab"
    },
    "Information": {
      "text-color": "#006f5f",
      "selected-text-color": "#006f5f"
    },
    "Warning": {
      "text-color": "#815b02",
      "selected-text-color": "#815b02"
    },
    "Alert": {
      "text-color": "#bb262a",
      "selected-text-color": "#bb262a",
      "bold": true
    },
    "Error": {
      "text-color": "#bb262a",
      "selected-text-color": "#bb262a"
    },
    "Others": {
      "text-color": "#3659ca",
      "selected-text-color": "#3659ca"
    }
  },
  "editor-colors": {
    "BackgroundColor": "#f8f4ff",
    "CodeFolding": "#eecae3",
    "BracketMatching": "#ebe7f5",
    "CurrentLine": "#ebe7f5",
    "IconBorder": "#ece7f9",
    "IndentationLine": "#c4bed2",
    "LineNumbers": "#89809b",
    "CurrentLineNumber": "#b9488b",
    "MarkBookmark": "#006f5f",
    "MarkBreakpointActive": "#bb262a",
    "MarkBreakpointReached": "#815b02",
    "MarkBreakpointDisabled": "#9f96b2",
    "MarkExecution": "#89809b",
    "MarkWarning": "#815b02",
    "MarkError": "#bb262a",
    "ModifiedLines": "#815b02",
    "ReplaceHighlight": "#b9488b",
    "SavedLines": "#2c6f2d",
    "SearchHighlight": "#dad0ed",
    "TextSelection": "#eecae3",
    "Separator": "#89809b",
    "SpellChecking": "#bb262a",
    "TabMarker": "#9f96b2",
    "TemplateBackground": "#d4cee2",
    "TemplatePlaceholder": "#c4bed2",
    "TemplateFocusedPlaceholder": "#b5afc4",
    "TemplateReadOnlyPlaceholder": "#ece7f9",
    "WordWrapMarker": "#9f96b2"
  }
}
