#!/usr/bin/env sh
# Build everything, then package each port into dist/: the VS Code .vsix, a Firefox .xpi
# per flavour, and a zip of every other port folder (theme files and README, without the
# assets/ screenshots).
set -e
cd "$(dirname "$0")"
rm -f dist/*.vsix dist/*.xpi dist/*.zip
node build.mjs "$@"
cp LICENSE ports/vscode/LICENSE
# The README is generated by build.mjs from template/README.md. Its image and link paths are
# relative to ports/vscode/, which vsce would otherwise resolve against the repository root.
REPO=$(node -p "require('./src/palette.json').repository")
(cd ports/vscode && npx --yes @vscode/vsce package --skip-license -o ../../dist/ \
  --baseContentUrl "$REPO/blob/main/ports/vscode" --baseImagesUrl "$REPO/raw/main/ports/vscode")
VERSION=$(node -p "require('./src/palette.json').version")
for dir in ports/firefox/*/; do
  name=$(basename "$dir")
  [ "$name" = assets ] && continue
  (cd "$dir" && zip -qr "../../../dist/darkberry-$name-$VERSION.xpi" manifest.json)
done
(cd ports/kitty && zip -qr "../../dist/darkberry-kitty-$VERSION.zip" . -x "assets/*")
(cd ports/ghostty && zip -qr "../../dist/darkberry-ghostty-$VERSION.zip" . -x "assets/*")
(cd ports/alacritty && zip -qr "../../dist/darkberry-alacritty-$VERSION.zip" . -x "assets/*")
(cd ports/tmux && zip -qr "../../dist/darkberry-tmux-$VERSION.zip" . -x "assets/*")
(cd ports/obsidian && zip -qr "../../dist/darkberry-obsidian-$VERSION.zip" . -x "assets/*")
(cd ports/kde && zip -qr "../../dist/darkberry-kde-$VERSION.zip" . -x "assets/*")
(cd ports/konsole && zip -qr "../../dist/darkberry-konsole-$VERSION.zip" . -x "assets/*")
(cd ports/nimbalyst && zip -qr "../../dist/darkberry-nimbalyst-$VERSION.zip" . -x "assets/*")
(cd ports/micro && zip -qr "../../dist/darkberry-micro-$VERSION.zip" . -x "assets/*")
(cd ports/kate && zip -qr "../../dist/darkberry-kate-$VERSION.zip" . -x "assets/*")
(cd ports/chrome && zip -qr "../../dist/darkberry-chrome-$VERSION.zip" . -x "assets/*")
(cd ports/notepadpp && zip -qr "../../dist/darkberry-notepadpp-$VERSION.zip" . -x "assets/*")
(cd ports/neovim && zip -qr "../../dist/darkberry-neovim-$VERSION.zip" . -x "assets/*")
(cd ports/gtk && zip -qr "../../dist/darkberry-gtk-$VERSION.zip" . -x "assets/*")
(cd ports/darktable && zip -qr "../../dist/darkberry-darktable-$VERSION.zip" . -x "assets/*")
(cd ports/gimp && zip -qr "../../dist/darkberry-gimp-$VERSION.zip" . -x "assets/*")
(cd ports/gpl && zip -qr "../../dist/darkberry-gpl-$VERSION.zip" . -x "assets/*")
(cd ports/starship && zip -qr "../../dist/darkberry-starship-$VERSION.zip" . -x "assets/*")
(cd ports/borders && zip -qr "../../dist/darkberry-borders-$VERSION.zip" . -x "assets/*")
(cd ports/lsd && zip -qr "../../dist/darkberry-lsd-$VERSION.zip" . -x "assets/*")
(cd ports/ls-colors && zip -qr "../../dist/darkberry-ls-colors-$VERSION.zip" . -x "assets/*")
(cd ports/tinted8 && zip -qr "../../dist/darkberry-tinted8-$VERSION.zip" . -x "assets/*")
(cd ports/base24 && zip -qr "../../dist/darkberry-base24-$VERSION.zip" . -x "assets/*")
(cd ports/btop && zip -qr "../../dist/darkberry-btop-$VERSION.zip" . -x "assets/*")
(cd ports/bat && zip -qr "../../dist/darkberry-bat-$VERSION.zip" . -x "assets/*")
ls dist
