{
  "metadata": {
    "copyright": [
      "SPDX-FileCopyrightText: Darkberry"
    ],
    "license": "SPDX-License-Identifier: MIT",
    "revision": 1,
    "name": "Lingonberry Blackwater"
  },
  "text-styles": {
    "Normal": {
      "text-color": "#f5dee4",
      "selected-text-color": "#f5dee4"
    },
    "Keyword": {
      "text-color": "#fd7ca5",
      "selected-text-color": "#fd7ca5",
      "bold": true
    },
    "Function": {
      "text-color": "#feafd4",
      "selected-text-color": "#feafd4"
    },
    "Variable": {
      "text-color": "#e7c5d8",
      "selected-text-color": "#e7c5d8"
    },
    "ControlFlow": {
      "text-color": "#fd7ca5",
      "selected-text-color": "#fd7ca5",
      "bold": true
    },
    "Operator": {
      "text-color": "#ccb5bb",
      "selected-text-color": "#ccb5bb"
    },
    "BuiltIn": {
      "text-color": "#baa8dc",
      "selected-text-color": "#baa8dc"
    },
    "Extension": {
      "text-color": "#feafd4",
      "selected-text-color": "#feafd4"
    },
    "Preprocessor": {
      "text-color": "#baa8dc",
      "selected-text-color": "#baa8dc"
    },
    "Attribute": {
      "text-color": "#e7af99",
      "selected-text-color": "#e7af99"
    },
    "Char": {
      "text-color": "#a3daa3",
      "selected-text-color": "#a3daa3"
    },
    "SpecialChar": {
      "text-color": "#9ed0c4",
      "selected-text-color": "#9ed0c4"
    },
    "String": {
      "text-color": "#a3daa3",
      "selected-text-color": "#a3daa3"
    },
    "VerbatimString": {
      "text-color": "#a3daa3",
      "selected-text-color": "#a3daa3"
    },
    "SpecialString": {
      "text-color": "#9ed0c4",
      "selected-text-color": "#9ed0c4"
    },
    "Import": {
      "text-color": "#baa8dc",
      "selected-text-color": "#baa8dc"
    },
    "DataType": {
      "text-color": "#ddb0ec",
      "selected-text-color": "#ddb0ec"
    },
    "DecVal": {
      "text-color": "#e8c98a",
      "selected-text-color": "#e8c98a"
    },
    "BaseN": {
      "text-color": "#e8c98a",
      "selected-text-color": "#e8c98a"
    },
    "Float": {
      "text-color": "#e8c98a",
      "selected-text-color": "#e8c98a"
    },
    "Constant": {
      "text-color": "#8fb0f2",
      "selected-text-color": "#8fb0f2"
    },
    "Comment": {
      "text-color": "#a98690",
      "selected-text-color": "#a98690",
      "italic": true
    },
    "Documentation": {
      "text-color": "#a98690",
      "selected-text-color": "#a98690",
      "italic": true
    },
    "Annotation": {
      "text-color": "#e7af99",
      "selected-text-color": "#e7af99"
    },
    "CommentVar": {
      "text-color": "#e7c5d8",
      "selected-text-color": "#e7c5d8"
    },
    "RegionMarker": {
      "text-color": "#baa8dc",
      "selected-text-color": "#baa8dc"
    },
    "Information": {
      "text-color": "#9ed0c4",
      "selected-text-color": "#9ed0c4"
    },
    "Warning": {
      "text-color": "#e8c98a",
      "selected-text-color": "#e8c98a"
    },
    "Alert": {
      "text-color": "#f06a6a",
      "selected-text-color": "#f06a6a",
      "bold": true
    },
    "Error": {
      "text-color": "#f06a6a",
      "selected-text-color": "#f06a6a"
    },
    "Others": {
      "text-color": "#8fb0f2",
      "selected-text-color": "#8fb0f2"
    }
  },
  "editor-colors": {
    "BackgroundColor": "#261017",
    "CodeFolding": "#4d2331",
    "BracketMatching": "#2a131a",
    "CurrentLine": "#2a131a",
    "IconBorder": "#200b12",
    "IndentationLine": "#3d212a",
    "LineNumbers": "#90757c",
    "CurrentLineNumber": "#ba4889",
    "MarkBookmark": "#9ed0c4",
    "MarkBreakpointActive": "#f06a6a",
    "MarkBreakpointReached": "#e8c98a",
    "MarkBreakpointDisabled": "#71555d",
    "MarkExecution": "#90757c",
    "MarkWarning": "#e8c98a",
    "MarkError": "#f06a6a",
    "ModifiedLines": "#e8c98a",
    "ReplaceHighlight": "#ba4889",
    "SavedLines": "#a3daa3",
    "SearchHighlight": "#473142",
    "TextSelection": "#4d2331",
    "Separator": "#90757c",
    "SpellChecking": "#f06a6a",
    "TabMarker": "#71555d",
    "TemplateBackground": "#301820",
    "TemplatePlaceholder": "#3d212a",
    "TemplateFocusedPlaceholder": "#4b2c35",
    "TemplateReadOnlyPlaceholder": "#200b12",
    "WordWrapMarker": "#71555d"
  }
}
