#!/bin/bash
# %FULL% for JankyBorders (the macOS window-border tool used with yabai and AeroSpace). %NOTE%
#
# Generated by build.mjs from src/ports/borders.sh. Do not edit ports/borders/.
# Install with:  cp %SLUG%.sh ~/.config/borders/bordersrc
# Then restart borders (brew services restart borders). Running this file while borders
# is already up sends it the new options instead, which is a quick way to try a flavour.
#
# Colours are 0xAARRGGBB. The focused window follows ui.border.active, which is the
# accent; every other window follows ui.border.inactive, which is quiet enough to sit
# beside the tiled gap without drawing the eye. Only the colours are the theme; width,
# style and hidpi are plain defaults, so change them freely.
borders style=round width=6.0 hidpi=on \
  active_color={ui.border.active} \
  inactive_color={ui.border.inactive}
