{
    "metadata": {
        "copyright": [
            "SPDX-FileCopyrightText: Darkberry"
        ],
        "license": "SPDX-License-Identifier: MIT",
        "revision": 1,
        "name": "%FULL%"
    },
    "text-styles": {
        "Normal": {
            "text-color": "{syntax.text}",
            "selected-text-color": "{syntax.text}"
        },
        "Keyword": {
            "text-color": "{syntax.keyword}",
            "selected-text-color": "{syntax.keyword}",
            "bold": true
        },
        "Function": {
            "text-color": "{syntax.function}",
            "selected-text-color": "{syntax.function}"
        },
        "Variable": {
            "text-color": "{syntax.variable}",
            "selected-text-color": "{syntax.variable}"
        },
        "ControlFlow": {
            "text-color": "{syntax.keyword}",
            "selected-text-color": "{syntax.keyword}",
            "bold": true
        },
        "Operator": {
            "text-color": "{syntax.operator}",
            "selected-text-color": "{syntax.operator}"
        },
        "BuiltIn": {
            "text-color": "{syntax.namespace}",
            "selected-text-color": "{syntax.namespace}"
        },
        "Extension": {
            "text-color": "{syntax.function}",
            "selected-text-color": "{syntax.function}"
        },
        "Preprocessor": {
            "text-color": "{syntax.namespace}",
            "selected-text-color": "{syntax.namespace}"
        },
        "Attribute": {
            "text-color": "{syntax.property}",
            "selected-text-color": "{syntax.property}"
        },
        "Char": {
            "text-color": "{syntax.string}",
            "selected-text-color": "{syntax.string}"
        },
        "SpecialChar": {
            "text-color": "{syntax.regex}",
            "selected-text-color": "{syntax.regex}"
        },
        "String": {
            "text-color": "{syntax.string}",
            "selected-text-color": "{syntax.string}"
        },
        "VerbatimString": {
            "text-color": "{syntax.string}",
            "selected-text-color": "{syntax.string}"
        },
        "SpecialString": {
            "text-color": "{syntax.regex}",
            "selected-text-color": "{syntax.regex}"
        },
        "Import": {
            "text-color": "{syntax.namespace}",
            "selected-text-color": "{syntax.namespace}"
        },
        "DataType": {
            "text-color": "{syntax.type}",
            "selected-text-color": "{syntax.type}"
        },
        "DecVal": {
            "text-color": "{syntax.number}",
            "selected-text-color": "{syntax.number}"
        },
        "BaseN": {
            "text-color": "{syntax.number}",
            "selected-text-color": "{syntax.number}"
        },
        "Float": {
            "text-color": "{syntax.number}",
            "selected-text-color": "{syntax.number}"
        },
        "Constant": {
            "text-color": "{syntax.constant}",
            "selected-text-color": "{syntax.constant}"
        },
        "Comment": {
            "text-color": "{syntax.comment}",
            "selected-text-color": "{syntax.comment}",
            "italic": true
        },
        "Documentation": {
            "text-color": "{syntax.comment}",
            "selected-text-color": "{syntax.comment}",
            "italic": true
        },
        "Annotation": {
            "text-color": "{syntax.property}",
            "selected-text-color": "{syntax.property}"
        },
        "CommentVar": {
            "text-color": "{syntax.variable}",
            "selected-text-color": "{syntax.variable}"
        },
        "RegionMarker": {
            "text-color": "{syntax.namespace}",
            "selected-text-color": "{syntax.namespace}"
        },
        "Information": {
            "text-color": "{ui.info}",
            "selected-text-color": "{ui.info}"
        },
        "Warning": {
            "text-color": "{ui.warning}",
            "selected-text-color": "{ui.warning}"
        },
        "Alert": {
            "text-color": "{ui.error}",
            "selected-text-color": "{ui.error}",
            "bold": true
        },
        "Error": {
            "text-color": "{syntax.error}",
            "selected-text-color": "{syntax.error}"
        },
        "Others": {
            "text-color": "{syntax.constant}",
            "selected-text-color": "{syntax.constant}"
        }
    },
    "editor-colors": {
        "BackgroundColor": "{ui.background}",
        "CodeFolding": "{ui.selection}",
        "BracketMatching": "{surface2}",
        "CurrentLine": "{surface0}",
        "IconBorder": "{ui.pane.secondary}",
        "IndentationLine": "{surface1}",
        "LineNumbers": "{ui.text.subtle}",
        "CurrentLineNumber": "{ui.accent}",
        "MarkBookmark": "{ui.info}",
        "MarkBreakpointActive": "{ui.error}",
        "MarkBreakpointReached": "{ui.warning}",
        "MarkBreakpointDisabled": "{overlay0}",
        "MarkExecution": "{ui.text.subtle}",
        "MarkWarning": "{ui.warning}",
        "MarkError": "{ui.error}",
        "ModifiedLines": "{ui.warning}",
        "ReplaceHighlight": "{ui.fill}",
        "SavedLines": "{ui.success}",
        "SearchHighlight": "{surface1}",
        "TextSelection": "{ui.selection}",
        "Separator": "{ui.border.inactive}",
        "SpellChecking": "{ui.error}",
        "TabMarker": "{overlay0}",
        "TemplateBackground": "{surface0}",
        "TemplatePlaceholder": "{surface1}",
        "TemplateFocusedPlaceholder": "{surface2}",
        "TemplateReadOnlyPlaceholder": "{ui.pane.secondary}",
        "WordWrapMarker": "{overlay0}"
    }
}
