# vim:ft=kitty
## name: %FULL%
## license: MIT
## blurb: %NOTE%

foreground {ui.text}
background {ui.background}
selection_foreground {ui.text}
selection_background {ui.selection}
cursor {ui.cursor}
cursor_text_color {ui.cursor.text}
url_color {ui.link}
active_border_color {ui.border.active}
inactive_border_color {ui.border.inactive}
bell_border_color {ui.bell}
wayland_titlebar_color {ui.pane.secondary}
macos_titlebar_color {ui.pane.secondary}
active_tab_foreground {ui.on.tab.indicator}
active_tab_background {ui.tab.indicator}
inactive_tab_foreground {ui.text.muted}
inactive_tab_background {ui.tab.inactive}
tab_bar_background {ui.pane.tertiary}
mark1_foreground {ui.mark.text}
mark1_background {ui.mark1}
mark2_foreground {ui.mark.text}
mark2_background {ui.mark2}
mark3_foreground {ui.mark.text}
mark3_background {ui.mark3}

color0 {ansi.0}
color8 {ansi.8}
color1 {ansi.1}
color9 {ansi.9}
color2 {ansi.2}
color10 {ansi.10}
color3 {ansi.3}
color11 {ansi.11}
color4 {ansi.4}
color12 {ansi.12}
color5 {ansi.5}
color13 {ansi.13}
color6 {ansi.6}
color14 {ansi.14}
color7 {ansi.7}
color15 {ansi.15}
color16 {terminal.color16}
color17 {terminal.color17}
