# vim:ft=kitty
## name: Blueberry Wisp
## license: MIT
## blurb: Blueberry tint of Wisp: light, neutrals leaned toward blueberry (base #f2f6ff).

foreground #2f3b58
background #f2f6ff
selection_foreground #2f3b58
selection_background #e9cce3
cursor #a63676
cursor_text_color #f2f6ff
url_color #026b80
active_border_color #b9488b
inactive_border_color #7a859f
bell_border_color #815b02
wayland_titlebar_color #e3eafb
macos_titlebar_color #e3eafb
active_tab_foreground #f2f6ff
active_tab_background #335adf
inactive_tab_foreground #4a5774
inactive_tab_background #e3eafb
tab_bar_background #d8e0f2
mark1_foreground #f2f6ff
mark1_background #6e52ab
mark2_foreground #f2f6ff
mark2_background #8c3eb2
mark3_foreground #f2f6ff
mark3_background #1d64a4

color0 #3d4965
color8 #4a5774
color1 #bb262a
color9 #c5352f
color2 #2c6f2d
color10 #327938
color3 #815b02
color11 #89650e
color4 #3659ca
color12 #4b60d3
color5 #bf0b64
color13 #cb216a
color6 #006f5f
color14 #12796a
color7 #aab3c7
color15 #b9c1d5
color16 #a24712
color17 #934b66
