# vim:ft=kitty
## name: Blueberry Fen
## license: MIT
## blurb: Blueberry tint of Fen: dark, neutrals leaned toward blueberry (base #2f3b58).

foreground #e3eaf9
background #2f3b58
selection_foreground #e3eaf9
selection_background #544b69
cursor #ffc4dd
cursor_text_color #1d2740
url_color #83d4db
active_border_color #dc67a7
inactive_border_color #808daa
bell_border_color #f0d6a0
wayland_titlebar_color #25304b
macos_titlebar_color #25304b
active_tab_foreground #1d2740
active_tab_background #9bb9ff
inactive_tab_foreground #b9c0d1
inactive_tab_background #25304b
tab_bar_background #1d2740
mark1_foreground #1d2740
mark1_background #c9b0e8
mark2_foreground #1d2740
mark2_background #edbbfe
mark3_foreground #1d2740
mark3_background #9cc6ea

color0 #4a5776
color8 #576585
color1 #fd8c85
color9 #fa7a71
color2 #bbe5b3
color10 #a1d99c
color3 #f0d6a0
color11 #e3c782
color4 #a4c3f6
color12 #8fb6f7
color5 #fe96b4
color13 #fd82a5
color6 #afdfdb
color14 #8bd5d1
color7 #b9c0d1
color15 #ccd4e4
color16 #f7bf9e
color17 #ecaed2
