{
  "metadata": {
    "copyright": [
      "SPDX-FileCopyrightText: Darkberry"
    ],
    "license": "SPDX-License-Identifier: MIT",
    "revision": 1,
    "name": "Darkberry Fen"
  },
  "text-styles": {
    "Normal": {
      "text-color": "#f2e6ee",
      "selected-text-color": "#f2e6ee"
    },
    "Keyword": {
      "text-color": "#fa99b4",
      "selected-text-color": "#fa99b4",
      "bold": true
    },
    "Function": {
      "text-color": "#ffc4dd",
      "selected-text-color": "#ffc4dd"
    },
    "Variable": {
      "text-color": "#e6b2d4",
      "selected-text-color": "#e6b2d4"
    },
    "ControlFlow": {
      "text-color": "#fa99b4",
      "selected-text-color": "#fa99b4",
      "bold": true
    },
    "Operator": {
      "text-color": "#ccbac5",
      "selected-text-color": "#ccbac5"
    },
    "BuiltIn": {
      "text-color": "#c9b0e8",
      "selected-text-color": "#c9b0e8"
    },
    "Extension": {
      "text-color": "#ffc4dd",
      "selected-text-color": "#ffc4dd"
    },
    "Preprocessor": {
      "text-color": "#c9b0e8",
      "selected-text-color": "#c9b0e8"
    },
    "Attribute": {
      "text-color": "#eabeaa",
      "selected-text-color": "#eabeaa"
    },
    "Char": {
      "text-color": "#b7e6b7",
      "selected-text-color": "#b7e6b7"
    },
    "SpecialChar": {
      "text-color": "#b0dfd9",
      "selected-text-color": "#b0dfd9"
    },
    "String": {
      "text-color": "#b7e6b7",
      "selected-text-color": "#b7e6b7"
    },
    "VerbatimString": {
      "text-color": "#b7e6b7",
      "selected-text-color": "#b7e6b7"
    },
    "SpecialString": {
      "text-color": "#b0dfd9",
      "selected-text-color": "#b0dfd9"
    },
    "Import": {
      "text-color": "#c9b0e8",
      "selected-text-color": "#c9b0e8"
    },
    "DataType": {
      "text-color": "#ecbcfc",
      "selected-text-color": "#ecbcfc"
    },
    "DecVal": {
      "text-color": "#f0d6a0",
      "selected-text-color": "#f0d6a0"
    },
    "BaseN": {
      "text-color": "#f0d6a0",
      "selected-text-color": "#f0d6a0"
    },
    "Float": {
      "text-color": "#f0d6a0",
      "selected-text-color": "#f0d6a0"
    },
    "Constant": {
      "text-color": "#a4c3f6",
      "selected-text-color": "#a4c3f6"
    },
    "Comment": {
      "text-color": "#bd9fb1",
      "selected-text-color": "#bd9fb1",
      "italic": true
    },
    "Documentation": {
      "text-color": "#bd9fb1",
      "selected-text-color": "#bd9fb1",
      "italic": true
    },
    "Annotation": {
      "text-color": "#eabeaa",
      "selected-text-color": "#eabeaa"
    },
    "CommentVar": {
      "text-color": "#e6b2d4",
      "selected-text-color": "#e6b2d4"
    },
    "RegionMarker": {
      "text-color": "#c9b0e8",
      "selected-text-color": "#c9b0e8"
    },
    "Information": {
      "text-color": "#b0dfd9",
      "selected-text-color": "#b0dfd9"
    },
    "Warning": {
      "text-color": "#f0d6a0",
      "selected-text-color": "#f0d6a0"
    },
    "Alert": {
      "text-color": "#ff8a8a",
      "selected-text-color": "#ff8a8a",
      "bold": true
    },
    "Error": {
      "text-color": "#ff8a8a",
      "selected-text-color": "#ff8a8a"
    },
    "Others": {
      "text-color": "#a4c3f6",
      "selected-text-color": "#a4c3f6"
    }
  },
  "editor-colors": {
    "BackgroundColor": "#4f3143",
    "CodeFolding": "#6e4457",
    "BracketMatching": "#7b5a6e",
    "CurrentLine": "#5d3e51",
    "IconBorder": "#402838",
    "IndentationLine": "#6c4c60",
    "LineNumbers": "#a28297",
    "CurrentLineNumber": "#fa99b4",
    "MarkBookmark": "#b0dfd9",
    "MarkBreakpointActive": "#ff8a8a",
    "MarkBreakpointReached": "#f0d6a0",
    "MarkBreakpointDisabled": "#8f6e82",
    "MarkExecution": "#a28297",
    "MarkWarning": "#f0d6a0",
    "MarkError": "#ff8a8a",
    "ModifiedLines": "#f0d6a0",
    "ReplaceHighlight": "#ba4889",
    "SavedLines": "#b7e6b7",
    "SearchHighlight": "#6c4c60",
    "TextSelection": "#6e4457",
    "Separator": "#a28297",
    "SpellChecking": "#ff8a8a",
    "TabMarker": "#8f6e82",
    "TemplateBackground": "#5d3e51",
    "TemplatePlaceholder": "#6c4c60",
    "TemplateFocusedPlaceholder": "#7b5a6e",
    "TemplateReadOnlyPlaceholder": "#402838",
    "WordWrapMarker": "#8f6e82"
  }
}
