{
  "metadata": {
    "copyright": [
      "SPDX-FileCopyrightText: Darkberry"
    ],
    "license": "SPDX-License-Identifier: MIT",
    "revision": 1,
    "name": "Darkberry Wisp"
  },
  "text-styles": {
    "Normal": {
      "text-color": "#4f3143",
      "selected-text-color": "#4f3143"
    },
    "Keyword": {
      "text-color": "#bf0b64",
      "selected-text-color": "#bf0b64",
      "bold": true
    },
    "Function": {
      "text-color": "#a83570",
      "selected-text-color": "#a83570"
    },
    "Variable": {
      "text-color": "#934b66",
      "selected-text-color": "#934b66"
    },
    "ControlFlow": {
      "text-color": "#bf0b64",
      "selected-text-color": "#bf0b64",
      "bold": true
    },
    "Operator": {
      "text-color": "#604656",
      "selected-text-color": "#604656"
    },
    "BuiltIn": {
      "text-color": "#7350a8",
      "selected-text-color": "#7350a8"
    },
    "Extension": {
      "text-color": "#a83570",
      "selected-text-color": "#a83570"
    },
    "Preprocessor": {
      "text-color": "#7350a8",
      "selected-text-color": "#7350a8"
    },
    "Attribute": {
      "text-color": "#435982",
      "selected-text-color": "#435982"
    },
    "Char": {
      "text-color": "#2c6f2d",
      "selected-text-color": "#2c6f2d"
    },
    "SpecialChar": {
      "text-color": "#006f5f",
      "selected-text-color": "#006f5f"
    },
    "String": {
      "text-color": "#2c6f2d",
      "selected-text-color": "#2c6f2d"
    },
    "VerbatimString": {
      "text-color": "#2c6f2d",
      "selected-text-color": "#2c6f2d"
    },
    "SpecialString": {
      "text-color": "#006f5f",
      "selected-text-color": "#006f5f"
    },
    "Import": {
      "text-color": "#7350a8",
      "selected-text-color": "#7350a8"
    },
    "DataType": {
      "text-color": "#8c3eb2",
      "selected-text-color": "#8c3eb2"
    },
    "DecVal": {
      "text-color": "#815b02",
      "selected-text-color": "#815b02"
    },
    "BaseN": {
      "text-color": "#815b02",
      "selected-text-color": "#815b02"
    },
    "Float": {
      "text-color": "#815b02",
      "selected-text-color": "#815b02"
    },
    "Constant": {
      "text-color": "#3659ca",
      "selected-text-color": "#3659ca"
    },
    "Comment": {
      "text-color": "#745b6a",
      "selected-text-color": "#745b6a",
      "italic": true
    },
    "Documentation": {
      "text-color": "#745b6a",
      "selected-text-color": "#745b6a",
      "italic": true
    },
    "Annotation": {
      "text-color": "#435982",
      "selected-text-color": "#435982"
    },
    "CommentVar": {
      "text-color": "#934b66",
      "selected-text-color": "#934b66"
    },
    "RegionMarker": {
      "text-color": "#7350a8",
      "selected-text-color": "#7350a8"
    },
    "Information": {
      "text-color": "#006f5f",
      "selected-text-color": "#006f5f"
    },
    "Warning": {
      "text-color": "#815b02",
      "selected-text-color": "#815b02"
    },
    "Alert": {
      "text-color": "#bb262a",
      "selected-text-color": "#bb262a",
      "bold": true
    },
    "Error": {
      "text-color": "#bb262a",
      "selected-text-color": "#bb262a"
    },
    "Others": {
      "text-color": "#3659ca",
      "selected-text-color": "#3659ca"
    }
  },
  "editor-colors": {
    "BackgroundColor": "#fbf4f8",
    "CodeFolding": "#f0cadd",
    "BracketMatching": "#f1e6ed",
    "CurrentLine": "#f1e6ed",
    "IconBorder": "#f3e6ef",
    "IndentationLine": "#d0bac8",
    "LineNumbers": "#967d8c",
    "CurrentLineNumber": "#b9488b",
    "MarkBookmark": "#006f5f",
    "MarkBreakpointActive": "#bb262a",
    "MarkBreakpointReached": "#815b02",
    "MarkBreakpointDisabled": "#ac93a2",
    "MarkExecution": "#967d8c",
    "MarkWarning": "#815b02",
    "MarkError": "#bb262a",
    "ModifiedLines": "#815b02",
    "ReplaceHighlight": "#b9488b",
    "SavedLines": "#2c6f2d",
    "SearchHighlight": "#ddd0e6",
    "TextSelection": "#f0cadd",
    "Separator": "#967d8c",
    "SpellChecking": "#bb262a",
    "TabMarker": "#ac93a2",
    "TemplateBackground": "#dfcbd8",
    "TemplatePlaceholder": "#d0bac8",
    "TemplateFocusedPlaceholder": "#c3abb9",
    "TemplateReadOnlyPlaceholder": "#f3e6ef",
    "WordWrapMarker": "#ac93a2"
  }
}
