# vim:ft=kitty
## name: Crowberry Fen
## license: MIT
## blurb: Crowberry tint of Fen: dark, neutrals leaned toward crowberry (base #403654).

foreground #ece7f7
background #403654
selection_foreground #ece7f7
selection_background #624765
cursor #ffc4dd
cursor_text_color #2c233d
url_color #83d4db
active_border_color #dc67a7
inactive_border_color #9187a6
bell_border_color #f0d6a0
wayland_titlebar_color #352b47
macos_titlebar_color #352b47
active_tab_foreground #2c233d
active_tab_background #c6a9fc
inactive_tab_foreground #c2bdce
inactive_tab_background #352b47
tab_bar_background #2c233d
mark1_foreground #2c233d
mark1_background #c9b0e8
mark2_foreground #2c233d
mark2_background #edbbfe
mark3_foreground #2c233d
mark3_background #9cc6ea

color0 #5c5172
color8 #6a5f80
color1 #fd8c85
color9 #fa7a71
color2 #bbe5b3
color10 #a1d99c
color3 #f0d6a0
color11 #e3c782
color4 #a4c3f6
color12 #8fb6f7
color5 #fe96b4
color13 #fd82a5
color6 #afdfdb
color14 #8bd5d1
color7 #c2bdce
color15 #d6d1e2
color16 #f7bf9e
color17 #ecaed2
