# vim:ft=kitty
## name: Crowberry Blackwater
## license: MIT
## blurb: Crowberry tint of Blackwater: dark, neutrals leaned toward crowberry (base #191126).

foreground #e7e2f2
background #191126
selection_foreground #e7e2f2
selection_background #42243d
cursor #feafd4
cursor_text_color #0f081b
url_color #86c0cc
active_border_color #ba4889
inactive_border_color #807990
bell_border_color #e8c98a
wayland_titlebar_color #130c20
macos_titlebar_color #130c20
active_tab_foreground #0f081b
active_tab_background #bb95fc
inactive_tab_foreground #beb9c9
inactive_tab_background #130c20
tab_bar_background #0f081b
mark1_foreground #0f081b
mark1_background #baa8dc
mark2_foreground #0f081b
mark2_background #ddb0ec
mark3_foreground #0f081b
mark3_background #7fb4e0

color0 #2c233c
color8 #382f4a
color1 #f06a6a
color9 #ed5858
color2 #a3daa3
color10 #87cf8e
color3 #e8c98a
color11 #dcbb6d
color4 #8fb0f2
color12 #7da4f4
color5 #fd7ca5
color13 #fc6796
color6 #9ed0c4
color14 #7cc7b8
color7 #beb9c9
color15 #d1cddc
color16 #f2ad8a
color17 #e7c5d8
