# vim:ft=kitty
## name: Crowberry Mire
## license: MIT
## blurb: Crowberry tint of Mire: dark, neutrals leaned toward crowberry (base #251d34).

foreground #e9e4f4
background #251d34
selection_foreground #e9e4f4
selection_background #4c2e48
cursor #feafd4
cursor_text_color #181025
url_color #86c0cc
active_border_color #be4c8d
inactive_border_color #8a839a
bell_border_color #e8c98a
wayland_titlebar_color #1e162c
macos_titlebar_color #1e162c
active_tab_foreground #181025
active_tab_background #bb95fc
inactive_tab_foreground #c3bece
inactive_tab_background #1e162c
tab_bar_background #181025
mark1_foreground #181025
mark1_background #baa8dc
mark2_foreground #181025
mark2_background #ddb0ec
mark3_foreground #181025
mark3_background #7fb4e0

color0 #342b45
color8 #403654
color1 #f06a6a
color9 #ed5858
color2 #a3daa3
color10 #87cf8e
color3 #e8c98a
color11 #dcbb6d
color4 #8fb0f2
color12 #7da4f4
color5 #fd7ca5
color13 #fc6796
color6 #9ed0c4
color14 #7cc7b8
color7 #c3bece
color15 #d6d2e1
color16 #f2ad8a
color17 #e7c5d8
