# vim:ft=kitty
## name: Crowberry Wisp
## license: MIT
## blurb: Crowberry tint of Wisp: light, neutrals leaned toward crowberry (base #f8f4ff).

foreground #403654
background #f8f4ff
selection_foreground #403654
selection_background #eecae3
cursor #a63676
cursor_text_color #f8f4ff
url_color #026b80
active_border_color #b9488b
inactive_border_color #89809b
bell_border_color #815b02
wayland_titlebar_color #ece7f9
macos_titlebar_color #ece7f9
active_tab_foreground #f8f4ff
active_tab_background #7f3fcd
inactive_tab_foreground #5c5170
inactive_tab_background #ece7f9
tab_bar_background #e2dcef
mark1_foreground #f8f4ff
mark1_background #6e52ab
mark2_foreground #f8f4ff
mark2_background #8c3eb2
mark3_foreground #f8f4ff
mark3_background #1d64a4

color0 #4d4361
color8 #5c5170
color1 #bb262a
color9 #c5352f
color2 #2c6f2d
color10 #327938
color3 #815b02
color11 #89650e
color4 #3659ca
color12 #4b60d3
color5 #bf0b64
color13 #cb216a
color6 #006f5f
color14 #12796a
color7 #b5afc4
color15 #c4bed2
color16 #a24712
color17 #934b66
