-- Darkberry Wisp for Neovim. Light. Text is a violet-leaning cousin of the paint colour.
--
-- Generated by build.mjs from src/ports/neovim.lua. Do not edit ports/neovim/.
-- Install with:  cp darkberry-wisp.lua ~/.config/nvim/colors/
-- ($XDG_CONFIG_HOME/nvim/colors/ on Linux and macOS, ~/AppData/Local/nvim/colors/ on
-- Windows; the same path inside a Flatpak or Snap Neovim, which read the host config).
-- Then  :colorscheme darkberry-wisp  or, in init.lua,  vim.cmd.colorscheme("darkberry-wisp").
-- Keep the file name: Neovim takes the scheme name from it and vim.g.colors_name below
-- has to match. Nothing to rename, no version to bump; a re-copy is a re-import.
--
-- Needs Neovim 0.9 or newer: vim.api.nvim_set_hl with `sp`, `undercurl` and `link`
-- (0.7), the Added/Changed/Removed groups and the @lsp.type.* captures (0.9). Needs
-- `termguicolors` on before the scheme loads (vim.o.termguicolors = true): the file
-- carries hex only, no cterm fallback, so on a 16- or 256-colour terminal without it
-- Neovim keeps its defaults. Every group is set with default = false, so a plugin
-- that defines its own highlights after this file wins, as it should.
--
-- Deliberately left unset: MsgArea (setting it breaks the cmdline redraw, neovim#17832);
-- NormalNC keeps the Normal background rather than dimming inactive windows, because
-- a dimmed pane would need a surface no role names; plugin groups (Telescope, nvim-cmp,
-- gitsigns, which-key) are not painted, since most of them link to the core groups below
-- and the rest would be palette names in a template; the cterm side of every group.
--
-- Host-owned pairings: none the file cannot set. Two fills are painted under syntax
-- text that keeps its own colour, as the roles intend: Visual (ui.selection, which
-- declares carriesCode 0.65) and Search (ui.search.matches, carriesCode 0.65); the
-- build measures both. DiffAdd, DiffChange, DiffDelete and DiffText carry code the
-- same way (ui.diff.*, carriesCode 0.65).
--
-- Differs from Catppuccin:
--   Visual is ui.selection alone, not surface1 with bold: bold under a selection changes
--   the glyphs, and the selection role already reads.
--   LineNr is ui.text.subtle, not surface1 (1.8:1 on Mocha's base; the guide asks for
--   line numbers people can read), and CursorLineNr is the accent, not lavender.
--   The gutter (LineNr, SignColumn, FoldColumn and their CursorLine* siblings) sits on
--   ui.pane.secondary, as Kate's IconBorder and micro's line-number do; Catppuccin
--   leaves it on base.
--   WinSeparator is ui.border.inactive (overlay1), not crust: a split edge has to be
--   seen at 3:1, and crust on base is 1.1:1.
--   PmenuSel is the fill under ui.on.fill (a row selection), not surface0 with bold;
--   PmenuMatch is ui.emphasis, not bold text.
--   IncSearch and CurSearch are ui.mark1 under ui.mark.text, not sky and red; Search is
--   the mark faded into the background, not sky at 30%.
--   TabLineSel is ui.tab.active with an underline in ui.tab.indicator, since a status
--   line cannot draw a tab's top border any other way; Catppuccin links it to Normal.
--   ErrorMsg is ui.on.error on ui.error, as micro's error bar, not red text.
--   Directory is `tint`, the accent as readable text, not blue.
--   Title and PmenuMatch share ui.emphasis (cherry); Catppuccin uses blue and bold.
--   Boolean, StorageClass and Structure follow the VS Code port (constant.language and
--   storage are keywords there), not peach and yellow.
--   PreProc, Include, Define, Macro and PreCondit are syntax.namespace, as Kate's
--   Preprocessor and Import and micro's preproc, not pink and mauve.
--   SpecialChar and @string.escape are syntax.number (VS Code: constant.character.escape),
--   not pink; Tag is syntax.link (a jump target), not lavender bold.
--   Todo is ui.warning bold on nothing, as micro's todo, not base on a flamingo fill.
--   Folded is ui.text.muted on ui.selection, the slot Kate's CodeFolding uses, not blue
--   on surface1.

vim.o.background = "light"
vim.cmd.highlight("clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd.syntax("reset") end
vim.g.colors_name = "darkberry-wisp"

local H = {}

-- Editor -----------------------------------------------------------------------
H.Normal = { fg = "#4f3143", bg = "#fbf4f8" }
H.NormalNC = { fg = "#4f3143", bg = "#fbf4f8" }
H.NormalFloat = { fg = "#4f3143", bg = "#f3e6ef" }
H.FloatBorder = { fg = "#967d8c", bg = "#f3e6ef" }
H.FloatTitle = { fg = "#694e5f", bg = "#f3e6ef", bold = true }
H.NormalSB = { fg = "#4f3143", bg = "#ebdae5" }
H.WinBar = { fg = "#4f3143", bg = "#f3e6ef" }
H.WinBarNC = { fg = "#694e5f", bg = "#ebdae5" }

H.Cursor = { fg = "#fbf4f8", bg = "#a83570" }
H.lCursor = { fg = "#fbf4f8", bg = "#a83570" }
H.CursorIM = { fg = "#fbf4f8", bg = "#a83570" }
H.TermCursor = { fg = "#fbf4f8", bg = "#a83570" }
-- An unfocused terminal's cursor is the one cursor without a role: it is drawn a step
-- down from the text so it is found but not mistaken for the live one.
H.TermCursorNC = { fg = "#fbf4f8", bg = "#967d8c" }

H.CursorLine = { bg = "#f1e6ed" }
H.CursorColumn = { bg = "#f1e6ed" }
-- Gutter: line numbers, signs and the fold column on ui.pane.secondary, current line
-- number in the accent, the rest ui.text.subtle (as Kate and micro).
H.LineNr = { fg = "#967d8c", bg = "#f3e6ef" }
H.LineNrAbove = { fg = "#967d8c", bg = "#f3e6ef" }
H.LineNrBelow = { fg = "#967d8c", bg = "#f3e6ef" }
H.CursorLineNr = { fg = "#b9488b", bg = "#f3e6ef", bold = true }
H.SignColumn = { fg = "#967d8c", bg = "#f3e6ef" }
H.CursorLineSign = { fg = "#967d8c", bg = "#f3e6ef" }
H.FoldColumn = { fg = "#967d8c", bg = "#f3e6ef" }
H.CursorLineFold = { fg = "#967d8c", bg = "#f3e6ef" }
H.Folded = { fg = "#694e5f", bg = "#f0cadd" }
-- colorcolumn is a structural stripe with no shared meaning (micro's color-column).
H.ColorColumn = { bg = "#dfcbd8" }

H.Visual = { bg = "#f0cadd" }
H.VisualNOS = { bg = "#f0cadd" }
H.Search = { bg = "#ddd0e6" }
H.IncSearch = { fg = "#fbf4f8", bg = "#7350a8" }
H.CurSearch = { fg = "#fbf4f8", bg = "#7350a8" }
H.Substitute = { fg = "#fbf4f8", bg = "#8c3eb2" }
-- Bracket match: the accent on surface1, as micro and Notepad++.
H.MatchParen = { fg = "#b9488b", bg = "#f1e6ed", bold = true }
H.QuickFixLine = { bg = "#f0cadd", bold = true }
-- Same-symbol highlights (LSP document highlight): a structural surface step, so the
-- symbol under the cursor is found without reading as a selection or a search hit.
H.LspReferenceText = { bg = "#d0bac8" }
H.LspReferenceRead = { bg = "#d0bac8" }
H.LspReferenceWrite = { bg = "#d0bac8", bold = true }

H.Pmenu = { fg = "#4f3143", bg = "#f3e6ef" }
H.PmenuSel = { fg = "#ffffff", bg = "#b9488b" }
H.PmenuKind = { fg = "#694e5f", bg = "#f3e6ef" }
H.PmenuKindSel = { fg = "#ffffff", bg = "#b9488b" }
H.PmenuExtra = { fg = "#694e5f", bg = "#f3e6ef" }
H.PmenuExtraSel = { fg = "#ffffff", bg = "#b9488b" }
H.PmenuMatch = { fg = "#a53f54", bg = "#f3e6ef", bold = true }
H.PmenuMatchSel = { fg = "#ffffff", bg = "#b9488b", bold = true }
-- Scrollbar: the popup already sits on ui.pane.secondary, so its track takes the next
-- surface step (structural) and the thumb overlay0, as every other port's scrollbar.
H.PmenuSbar = { bg = "#dfcbd8" }
H.PmenuThumb = { bg = "#ac93a2" }
H.WildMenu = { fg = "#ffffff", bg = "#b9488b" }

H.StatusLine = { fg = "#4f3143", bg = "#f3e6ef" }
H.StatusLineNC = { fg = "#694e5f", bg = "#f3e6ef" }
H.TabLine = { fg = "#694e5f", bg = "#f3e6ef" }
H.TabLineFill = { bg = "#ebdae5" }
H.TabLineSel = { fg = "#4f3143", bg = "#fbf4f8", underline = true, sp = "#d21570" }
H.WinSeparator = { fg = "#967d8c", bg = "#fbf4f8" }
H.VertSplit = { fg = "#967d8c", bg = "#fbf4f8" }
H.MsgSeparator = { fg = "#967d8c", bg = "#fbf4f8" }

H.Title = { fg = "#a53f54", bold = true }
H.Directory = { fg = "#d21570" }
H.Question = { fg = "#006f5f" }
H.MoreMsg = { fg = "#006f5f" }
H.ModeMsg = { fg = "#4f3143", bold = true }
H.ErrorMsg = { fg = "#ffffff", bg = "#bb262a", bold = true }
H.WarningMsg = { fg = "#815b02" }
H.OkMsg = { fg = "#2c6f2d" }
H.NonText = { fg = "#967d8c" }
H.SpecialKey = { fg = "#967d8c" }
-- Listchars (tab, trail, nbsp) and the end-of-buffer tildes are marker glyphs with
-- no shared meaning: overlay0 as Kate's TabMarker and WordWrapMarker, surface1 for
-- the filler tildes so they sit behind the text instead of beside it.
H.Whitespace = { fg = "#ac93a2" }
H.EndOfBuffer = { fg = "#d0bac8" }
H.Conceal = { fg = "#967d8c" }

H.DiffAdd = { bg = "#d6dcd3" }
H.DiffChange = { bg = "#efe5df" }
H.DiffDelete = { fg = "#9e4116", bg = "#ead4cf" }
H.DiffText = { bg = "#e5d8cc" }
H.Added = { fg = "#2c6f2d" }
H.Changed = { fg = "#815b02" }
H.Removed = { fg = "#9e4116" }
H.diffAdded = { fg = "#2c6f2d" }
H.diffChanged = { fg = "#815b02" }
H.diffRemoved = { fg = "#9e4116" }
H.diffFile = { fg = "#a83570" }
H.diffOldFile = { fg = "#a83570" }
H.diffNewFile = { fg = "#a83570" }
H.diffLine = { fg = "#745b6a" }
H.diffIndexLine = { fg = "#745b6a" }

H.DiagnosticError = { fg = "#bb262a" }
H.DiagnosticWarn = { fg = "#815b02" }
H.DiagnosticInfo = { fg = "#006f5f" }
H.DiagnosticHint = { fg = "#2c6f2d" }
H.DiagnosticOk = { fg = "#2c6f2d" }
H.DiagnosticVirtualTextError = { fg = "#bb262a" }
H.DiagnosticVirtualTextWarn = { fg = "#815b02" }
H.DiagnosticVirtualTextInfo = { fg = "#006f5f" }
H.DiagnosticVirtualTextHint = { fg = "#2c6f2d" }
H.DiagnosticVirtualTextOk = { fg = "#2c6f2d" }
H.DiagnosticUnderlineError = { sp = "#bb262a", undercurl = true }
H.DiagnosticUnderlineWarn = { sp = "#815b02", undercurl = true }
H.DiagnosticUnderlineInfo = { sp = "#006f5f", undercurl = true }
H.DiagnosticUnderlineHint = { sp = "#2c6f2d", undercurl = true }
H.DiagnosticUnderlineOk = { sp = "#2c6f2d", undercurl = true }
H.DiagnosticSignError = { fg = "#bb262a", bg = "#f3e6ef" }
H.DiagnosticSignWarn = { fg = "#815b02", bg = "#f3e6ef" }
H.DiagnosticSignInfo = { fg = "#006f5f", bg = "#f3e6ef" }
H.DiagnosticSignHint = { fg = "#2c6f2d", bg = "#f3e6ef" }
H.DiagnosticSignOk = { fg = "#2c6f2d", bg = "#f3e6ef" }
H.DiagnosticFloatingError = { fg = "#bb262a", bg = "#f3e6ef" }
H.DiagnosticFloatingWarn = { fg = "#815b02", bg = "#f3e6ef" }
H.DiagnosticFloatingInfo = { fg = "#006f5f", bg = "#f3e6ef" }
H.DiagnosticFloatingHint = { fg = "#2c6f2d", bg = "#f3e6ef" }
H.DiagnosticFloatingOk = { fg = "#2c6f2d", bg = "#f3e6ef" }
H.DiagnosticDeprecated = { fg = "#745b6a", strikethrough = true }
H.DiagnosticUnnecessary = { fg = "#745b6a" }

H.SpellBad = { sp = "#bb262a", undercurl = true }
H.SpellCap = { sp = "#815b02", undercurl = true }
H.SpellLocal = { sp = "#006f5f", undercurl = true }
H.SpellRare = { sp = "#2c6f2d", undercurl = true }

H.healthError = { fg = "#bb262a" }
H.healthWarning = { fg = "#815b02" }
H.healthSuccess = { fg = "#2c6f2d" }
H.qfFileName = { fg = "#a83570" }
H.qfLineNr = { fg = "#967d8c" }
H.debugPC = { bg = "#f1e6ed" }
H.debugBreakpoint = { fg = "#bb262a", bg = "#f3e6ef" }

-- Syntax -----------------------------------------------------------------------
-- The scope to role mapping of src/vscode/template.json, so int is syntax.type here
-- as in every other editor.
H.Comment = { fg = "#745b6a", italic = true }
H.SpecialComment = { fg = "#745b6a", italic = true }
H.Constant = { fg = "#3659ca" }
H.String = { fg = "#2c6f2d" }
H.Character = { fg = "#2c6f2d" }
H.Number = { fg = "#815b02" }
H.Float = { fg = "#815b02" }
H.Boolean = { fg = "#bf0b64" }
H.Identifier = { fg = "#934b66" }
H.Function = { fg = "#a83570" }
H.Statement = { fg = "#bf0b64" }
H.Conditional = { fg = "#bf0b64" }
H.Repeat = { fg = "#bf0b64" }
H.Label = { fg = "#bf0b64" }
H.Operator = { fg = "#604656" }
H.Keyword = { fg = "#bf0b64" }
H.Exception = { fg = "#bf0b64" }
H.PreProc = { fg = "#7350a8" }
H.Include = { fg = "#7350a8" }
H.Define = { fg = "#7350a8" }
H.Macro = { fg = "#7350a8" }
H.PreCondit = { fg = "#7350a8" }
H.Type = { fg = "#8c3eb2" }
H.StorageClass = { fg = "#bf0b64" }
H.Structure = { fg = "#bf0b64" }
H.Typedef = { fg = "#8c3eb2" }
H.Special = { fg = "#006f5f" }
H.SpecialChar = { fg = "#815b02" }
H.Tag = { fg = "#026b80" }
H.Delimiter = { fg = "#8f7685" }
H.Debug = { fg = "#006f5f" }
H.Underlined = { fg = "#026b80", underline = true }
H.Bold = { bold = true }
H.Italic = { italic = true }
H.Ignore = { fg = "#967d8c" }
H.Error = { fg = "#bb262a" }
H.Todo = { fg = "#815b02", bold = true }

-- Tree-sitter captures. Neovim 0.9 names first, the 0.10 renames beside them, so one
-- file serves both.
H["@variable"] = { fg = "#934b66" }
H["@variable.builtin"] = { fg = "#934b66", italic = true }
H["@variable.parameter"] = { fg = "#934b66" }
H["@variable.member"] = { fg = "#435982" }
H["@parameter"] = { fg = "#934b66" }
H["@field"] = { fg = "#435982" }
H["@property"] = { fg = "#435982" }
H["@constant"] = { fg = "#3659ca" }
H["@constant.builtin"] = { fg = "#bf0b64" }
H["@constant.macro"] = { fg = "#7350a8" }
H["@module"] = { fg = "#7350a8" }
H["@module.builtin"] = { fg = "#7350a8" }
H["@namespace"] = { fg = "#7350a8" }
H["@label"] = { fg = "#bf0b64" }
H["@string"] = { fg = "#2c6f2d" }
H["@string.documentation"] = { fg = "#745b6a", italic = true }
H["@string.regex"] = { fg = "#006f5f" }
H["@string.regexp"] = { fg = "#006f5f" }
H["@string.escape"] = { fg = "#815b02" }
H["@string.special"] = { fg = "#006f5f" }
H["@string.special.symbol"] = { fg = "#3659ca" }
H["@string.special.url"] = { fg = "#026b80", underline = true }
H["@character"] = { fg = "#2c6f2d" }
H["@character.special"] = { fg = "#006f5f" }
H["@number"] = { fg = "#815b02" }
H["@number.float"] = { fg = "#815b02" }
H["@float"] = { fg = "#815b02" }
H["@boolean"] = { fg = "#bf0b64" }
H["@type"] = { fg = "#8c3eb2" }
H["@type.builtin"] = { fg = "#8c3eb2" }
H["@type.definition"] = { fg = "#8c3eb2" }
H["@type.qualifier"] = { fg = "#bf0b64" }
H["@storageclass"] = { fg = "#bf0b64" }
H["@attribute"] = { fg = "#a83570" }
H["@attribute.builtin"] = { fg = "#a83570" }
H["@function"] = { fg = "#a83570" }
H["@function.builtin"] = { fg = "#a83570" }
H["@function.call"] = { fg = "#a83570" }
H["@function.macro"] = { fg = "#a83570" }
H["@function.method"] = { fg = "#a83570" }
H["@function.method.call"] = { fg = "#a83570" }
H["@method"] = { fg = "#a83570" }
H["@method.call"] = { fg = "#a83570" }
H["@constructor"] = { fg = "#a83570" }
H["@operator"] = { fg = "#604656" }
H["@keyword"] = { fg = "#bf0b64" }
H["@keyword.coroutine"] = { fg = "#bf0b64" }
H["@keyword.function"] = { fg = "#bf0b64" }
H["@keyword.operator"] = { fg = "#bf0b64" }
H["@keyword.import"] = { fg = "#7350a8" }
H["@keyword.type"] = { fg = "#bf0b64" }
H["@keyword.modifier"] = { fg = "#bf0b64" }
H["@keyword.repeat"] = { fg = "#bf0b64" }
H["@keyword.return"] = { fg = "#bf0b64" }
H["@keyword.debug"] = { fg = "#006f5f" }
H["@keyword.exception"] = { fg = "#bf0b64" }
H["@keyword.conditional"] = { fg = "#bf0b64" }
H["@keyword.conditional.ternary"] = { fg = "#bf0b64" }
H["@keyword.directive"] = { fg = "#7350a8" }
H["@keyword.directive.define"] = { fg = "#7350a8" }
H["@keyword.export"] = { fg = "#bf0b64" }
H["@conditional"] = { fg = "#bf0b64" }
H["@repeat"] = { fg = "#bf0b64" }
H["@exception"] = { fg = "#bf0b64" }
H["@include"] = { fg = "#7350a8" }
H["@define"] = { fg = "#7350a8" }
H["@preproc"] = { fg = "#7350a8" }
H["@debug"] = { fg = "#006f5f" }
H["@punctuation"] = { fg = "#8f7685" }
H["@punctuation.delimiter"] = { fg = "#8f7685" }
H["@punctuation.bracket"] = { fg = "#8f7685" }
H["@punctuation.special"] = { fg = "#bf0b64" }
H["@comment"] = { fg = "#745b6a", italic = true }
H["@comment.documentation"] = { fg = "#745b6a", italic = true }
H["@comment.error"] = { fg = "#bb262a", bold = true }
H["@comment.warning"] = { fg = "#815b02", bold = true }
H["@comment.todo"] = { fg = "#815b02", bold = true }
H["@comment.note"] = { fg = "#006f5f", bold = true }
H["@text.danger"] = { fg = "#bb262a", bold = true }
H["@text.warning"] = { fg = "#815b02", bold = true }
H["@text.todo"] = { fg = "#815b02", bold = true }
H["@text.note"] = { fg = "#006f5f", bold = true }
H["@tag"] = { fg = "#a83570" }
H["@tag.builtin"] = { fg = "#a83570" }
H["@tag.attribute"] = { fg = "#3659ca" }
H["@tag.delimiter"] = { fg = "#8f7685" }
H["@markup.heading"] = { fg = "#a83570", bold = true }
H["@markup.strong"] = { fg = "#3659ca", bold = true }
H["@markup.italic"] = { fg = "#bf0b64", italic = true }
H["@markup.strikethrough"] = { strikethrough = true }
H["@markup.underline"] = { underline = true }
H["@markup.raw"] = { fg = "#2c6f2d" }
H["@markup.raw.block"] = { fg = "#2c6f2d" }
H["@markup.link"] = { fg = "#026b80" }
H["@markup.link.label"] = { fg = "#026b80" }
H["@markup.link.url"] = { fg = "#026b80", underline = true }
H["@markup.list"] = { fg = "#8f7685" }
H["@markup.list.checked"] = { fg = "#2c6f2d" }
H["@markup.list.unchecked"] = { fg = "#967d8c" }
H["@markup.quote"] = { fg = "#745b6a" }
H["@markup.math"] = { fg = "#815b02" }
H["@markup.environment"] = { fg = "#7350a8" }
H["@text.title"] = { fg = "#a83570", bold = true }
H["@text.strong"] = { fg = "#3659ca", bold = true }
H["@text.emphasis"] = { fg = "#bf0b64", italic = true }
H["@text.strike"] = { strikethrough = true }
H["@text.underline"] = { underline = true }
H["@text.literal"] = { fg = "#2c6f2d" }
H["@text.uri"] = { fg = "#026b80", underline = true }
H["@text.reference"] = { fg = "#026b80" }
H["@text.quote"] = { fg = "#745b6a" }
H["@text.math"] = { fg = "#815b02" }
H["@text.environment"] = { fg = "#7350a8" }
H["@diff.plus"] = { fg = "#2c6f2d" }
H["@diff.minus"] = { fg = "#9e4116" }
H["@diff.delta"] = { fg = "#815b02" }
H["@text.diff.add"] = { fg = "#2c6f2d" }
H["@text.diff.delete"] = { fg = "#9e4116" }
H["@none"] = {}

-- LSP semantic tokens, mapped to the same roles as the captures they refine.
H["@lsp.type.namespace"] = { fg = "#7350a8" }
H["@lsp.type.class"] = { fg = "#8c3eb2" }
H["@lsp.type.struct"] = { fg = "#8c3eb2" }
H["@lsp.type.enum"] = { fg = "#8c3eb2" }
H["@lsp.type.interface"] = { fg = "#8c3eb2" }
H["@lsp.type.type"] = { fg = "#8c3eb2" }
H["@lsp.type.typeParameter"] = { fg = "#8c3eb2" }
H["@lsp.type.enumMember"] = { fg = "#3659ca" }
H["@lsp.type.function"] = { fg = "#a83570" }
H["@lsp.type.method"] = { fg = "#a83570" }
H["@lsp.type.decorator"] = { fg = "#a83570" }
H["@lsp.type.macro"] = { fg = "#a83570" }
H["@lsp.type.variable"] = { fg = "#934b66" }
H["@lsp.type.parameter"] = { fg = "#934b66" }
H["@lsp.type.property"] = { fg = "#435982" }
H["@lsp.type.keyword"] = { fg = "#bf0b64" }
H["@lsp.type.modifier"] = { fg = "#bf0b64" }
H["@lsp.type.operator"] = { fg = "#604656" }
H["@lsp.type.string"] = { fg = "#2c6f2d" }
H["@lsp.type.number"] = { fg = "#815b02" }
H["@lsp.type.comment"] = { fg = "#745b6a", italic = true }
H["@lsp.mod.deprecated"] = { fg = "#745b6a", strikethrough = true }

for group, spec in pairs(H) do
  vim.api.nvim_set_hl(0, group, spec)
end

-- Terminal palette: ANSI 0-15 exactly as the kitty port.
vim.g.terminal_color_0 = "#5a4050"
vim.g.terminal_color_1 = "#bb262a"
vim.g.terminal_color_2 = "#2c6f2d"
vim.g.terminal_color_3 = "#815b02"
vim.g.terminal_color_4 = "#3659ca"
vim.g.terminal_color_5 = "#bf0b64"
vim.g.terminal_color_6 = "#006f5f"
vim.g.terminal_color_7 = "#c3abb9"
vim.g.terminal_color_8 = "#694e5f"
vim.g.terminal_color_9 = "#c5352f"
vim.g.terminal_color_10 = "#327938"
vim.g.terminal_color_11 = "#89650e"
vim.g.terminal_color_12 = "#4b60d3"
vim.g.terminal_color_13 = "#cb216a"
vim.g.terminal_color_14 = "#12796a"
vim.g.terminal_color_15 = "#d0bac8"
