# vim:ft=kitty
## name: Lingonberry Wisp
## license: MIT
## blurb: Lingonberry tint of Wisp: light, neutrals leaned toward lingonberry (base #fff3f6).

foreground #572c3b
background #fff3f6
selection_foreground #572c3b
selection_background #f3c9dc
cursor #a63676
cursor_text_color #fff3f6
url_color #026b80
active_border_color #b9488b
inactive_border_color #9b7c84
bell_border_color #815b02
wayland_titlebar_color #f9e4ea
macos_titlebar_color #f9e4ea
active_tab_foreground #fff3f6
active_tab_background #bf0b65
inactive_tab_foreground #744956
inactive_tab_background #f9e4ea
tab_bar_background #efd9df
mark1_foreground #fff3f6
mark1_background #6e52ab
mark2_foreground #fff3f6
mark2_background #8c3eb2
mark3_foreground #fff3f6
mark3_background #1d64a4

color0 #653b48
color8 #744956
color1 #bb262a
color9 #c5352f
color2 #2c6f2d
color10 #327938
color3 #815b02
color11 #89650e
color4 #3659ca
color12 #4b60d3
color5 #bf0b64
color13 #cb216a
color6 #006f5f
color14 #12796a
color7 #c5abb2
color15 #d3bac0
color16 #a24712
color17 #934b66
