# vim:ft=kitty
## name: Lingonberry Fen
## license: MIT
## blurb: Lingonberry tint of Fen: dark, neutrals leaned toward lingonberry (base #55323d).

foreground #fae3e9
background #55323d
selection_foreground #fae3e9
selection_background #734452
cursor #ffc4dd
cursor_text_color #3d2029
url_color #83d4db
active_border_color #dc67a7
inactive_border_color #a6828c
bell_border_color #f0d6a0
wayland_titlebar_color #482832
macos_titlebar_color #482832
active_tab_foreground #3d2029
active_tab_background #f999b7
inactive_tab_foreground #d2b8bf
inactive_tab_background #482832
tab_bar_background #3d2029
mark1_foreground #3d2029
mark1_background #c9b0e8
mark2_foreground #3d2029
mark2_background #edbbfe
mark3_foreground #3d2029
mark3_background #9cc6ea

color0 #734d58
color8 #825b67
color1 #fd8c85
color9 #fa7a71
color2 #bbe5b3
color10 #a1d99c
color3 #f0d6a0
color11 #e3c782
color4 #a4c3f6
color12 #8fb6f7
color5 #fe96b4
color13 #fd82a5
color6 #afdfdb
color14 #8bd5d1
color7 #d2b8bf
color15 #e5ccd3
color16 #f7bf9e
color17 #ecaed2
