# vim:ft=kitty
## name: Lingonberry Blackwater
## license: MIT
## blurb: Lingonberry tint of Blackwater: dark, neutrals leaned toward lingonberry (base #261017).

foreground #f5dee4
background #261017
selection_foreground #f5dee4
selection_background #4d2331
cursor #feafd4
cursor_text_color #1a070d
url_color #86c0cc
active_border_color #ba4889
inactive_border_color #90757c
bell_border_color #e8c98a
wayland_titlebar_color #200b12
macos_titlebar_color #200b12
active_tab_foreground #1a070d
active_tab_background #fc7ca8
inactive_tab_foreground #ccb5bb
inactive_tab_background #200b12
tab_bar_background #1a070d
mark1_foreground #1a070d
mark1_background #baa8dc
mark2_foreground #1a070d
mark2_background #ddb0ec
mark3_foreground #1a070d
mark3_background #7fb4e0

color0 #3d212a
color8 #4b2c35
color1 #f06a6a
color9 #ed5858
color2 #a3daa3
color10 #87cf8e
color3 #e8c98a
color11 #dcbb6d
color4 #8fb0f2
color12 #7da4f4
color5 #fd7ca5
color13 #fc6796
color6 #9ed0c4
color14 #7cc7b8
color7 #ccb5bb
color15 #e0c9cf
color16 #f2ad8a
color17 #e7c5d8
