# vim:ft=kitty
## name: Lingonberry Mire
## license: MIT
## blurb: Lingonberry tint of Mire: dark, neutrals leaned toward lingonberry (base #341c23).

foreground #f7e0e6
background #341c23
selection_foreground #f7e0e6
selection_background #582d3a
cursor #feafd4
cursor_text_color #250f16
url_color #86c0cc
active_border_color #be4c8d
inactive_border_color #997f86
bell_border_color #e8c98a
wayland_titlebar_color #2c141c
macos_titlebar_color #2c141c
active_tab_foreground #250f16
active_tab_background #fc7ca8
inactive_tab_foreground #d1bac0
inactive_tab_background #2c141c
tab_bar_background #250f16
mark1_foreground #250f16
mark1_background #baa8dc
mark2_foreground #250f16
mark2_background #ddb0ec
mark3_foreground #250f16
mark3_background #7fb4e0

color0 #462832
color8 #55323d
color1 #f06a6a
color9 #ed5858
color2 #a3daa3
color10 #87cf8e
color3 #e8c98a
color11 #dcbb6d
color4 #8fb0f2
color12 #7da4f4
color5 #fd7ca5
color13 #fc6796
color6 #9ed0c4
color14 #7cc7b8
color7 #d1bac0
color15 #e5ced4
color16 #f2ad8a
color17 #e7c5d8
