{
  "metadata": {
    "copyright": [
      "SPDX-FileCopyrightText: Darkberry"
    ],
    "license": "SPDX-License-Identifier: MIT",
    "revision": 1,
    "name": "Blueberry Mire"
  },
  "text-styles": {
    "Normal": {
      "text-color": "#e0e7f6",
      "selected-text-color": "#e0e7f6"
    },
    "Keyword": {
      "text-color": "#fd7ca5",
      "selected-text-color": "#fd7ca5",
      "bold": true
    },
    "Function": {
      "text-color": "#feafd4",
      "selected-text-color": "#feafd4"
    },
    "Variable": {
      "text-color": "#e7c5d8",
      "selected-text-color": "#e7c5d8"
    },
    "ControlFlow": {
      "text-color": "#fd7ca5",
      "selected-text-color": "#fd7ca5",
      "bold": true
    },
    "Operator": {
      "text-color": "#bac1d0",
      "selected-text-color": "#bac1d0"
    },
    "BuiltIn": {
      "text-color": "#baa8dc",
      "selected-text-color": "#baa8dc"
    },
    "Extension": {
      "text-color": "#feafd4",
      "selected-text-color": "#feafd4"
    },
    "Preprocessor": {
      "text-color": "#baa8dc",
      "selected-text-color": "#baa8dc"
    },
    "Attribute": {
      "text-color": "#e1b39f",
      "selected-text-color": "#e1b39f"
    },
    "Char": {
      "text-color": "#a3daa3",
      "selected-text-color": "#a3daa3"
    },
    "SpecialChar": {
      "text-color": "#9ed0c4",
      "selected-text-color": "#9ed0c4"
    },
    "String": {
      "text-color": "#a3daa3",
      "selected-text-color": "#a3daa3"
    },
    "VerbatimString": {
      "text-color": "#a3daa3",
      "selected-text-color": "#a3daa3"
    },
    "SpecialString": {
      "text-color": "#9ed0c4",
      "selected-text-color": "#9ed0c4"
    },
    "Import": {
      "text-color": "#baa8dc",
      "selected-text-color": "#baa8dc"
    },
    "DataType": {
      "text-color": "#ddb0ec",
      "selected-text-color": "#ddb0ec"
    },
    "DecVal": {
      "text-color": "#e8c98a",
      "selected-text-color": "#e8c98a"
    },
    "BaseN": {
      "text-color": "#e8c98a",
      "selected-text-color": "#e8c98a"
    },
    "Float": {
      "text-color": "#e8c98a",
      "selected-text-color": "#e8c98a"
    },
    "Constant": {
      "text-color": "#8fb0f2",
      "selected-text-color": "#8fb0f2"
    },
    "Comment": {
      "text-color": "#8b98b5",
      "selected-text-color": "#8b98b5",
      "italic": true
    },
    "Documentation": {
      "text-color": "#8b98b5",
      "selected-text-color": "#8b98b5",
      "italic": true
    },
    "Annotation": {
      "text-color": "#e1b39f",
      "selected-text-color": "#e1b39f"
    },
    "CommentVar": {
      "text-color": "#e7c5d8",
      "selected-text-color": "#e7c5d8"
    },
    "RegionMarker": {
      "text-color": "#baa8dc",
      "selected-text-color": "#baa8dc"
    },
    "Information": {
      "text-color": "#9ed0c4",
      "selected-text-color": "#9ed0c4"
    },
    "Warning": {
      "text-color": "#e8c98a",
      "selected-text-color": "#e8c98a"
    },
    "Alert": {
      "text-color": "#f06a6a",
      "selected-text-color": "#f06a6a",
      "bold": true
    },
    "Error": {
      "text-color": "#f06a6a",
      "selected-text-color": "#f06a6a"
    },
    "Others": {
      "text-color": "#8fb0f2",
      "selected-text-color": "#8fb0f2"
    }
  },
  "editor-colors": {
    "BackgroundColor": "#192237",
    "CodeFolding": "#42324b",
    "BracketMatching": "#1a2439",
    "CurrentLine": "#1a2439",
    "IconBorder": "#111a2f",
    "IndentationLine": "#253049",
    "LineNumbers": "#7d879d",
    "CurrentLineNumber": "#be4c8d",
    "MarkBookmark": "#9ed0c4",
    "MarkBreakpointActive": "#f06a6a",
    "MarkBreakpointReached": "#e8c98a",
    "MarkBreakpointDisabled": "#657087",
    "MarkExecution": "#7d879d",
    "MarkWarning": "#e8c98a",
    "MarkError": "#f06a6a",
    "ModifiedLines": "#e8c98a",
    "ReplaceHighlight": "#be4c8d",
    "SavedLines": "#a3daa3",
    "SearchHighlight": "#3c3f5b",
    "TextSelection": "#42324b",
    "Separator": "#7d879d",
    "SpellChecking": "#f06a6a",
    "TabMarker": "#657087",
    "TemplateBackground": "#1d273e",
    "TemplatePlaceholder": "#253049",
    "TemplateFocusedPlaceholder": "#2f3b58",
    "TemplateReadOnlyPlaceholder": "#111a2f",
    "WordWrapMarker": "#657087"
  }
}
