{
  "metadata": {
    "copyright": [
      "SPDX-FileCopyrightText: Darkberry"
    ],
    "license": "SPDX-License-Identifier: MIT",
    "revision": 1,
    "name": "Blueberry Wisp"
  },
  "text-styles": {
    "Normal": {
      "text-color": "#2f3b58",
      "selected-text-color": "#2f3b58"
    },
    "Keyword": {
      "text-color": "#bf0b64",
      "selected-text-color": "#bf0b64",
      "bold": true
    },
    "Function": {
      "text-color": "#a63676",
      "selected-text-color": "#a63676"
    },
    "Variable": {
      "text-color": "#934b66",
      "selected-text-color": "#934b66"
    },
    "ControlFlow": {
      "text-color": "#bf0b64",
      "selected-text-color": "#bf0b64",
      "bold": true
    },
    "Operator": {
      "text-color": "#424f6b",
      "selected-text-color": "#424f6b"
    },
    "BuiltIn": {
      "text-color": "#6e52ab",
      "selected-text-color": "#6e52ab"
    },
    "Extension": {
      "text-color": "#a63676",
      "selected-text-color": "#a63676"
    },
    "Preprocessor": {
      "text-color": "#6e52ab",
      "selected-text-color": "#6e52ab"
    },
    "Attribute": {
      "text-color": "#345e8c",
      "selected-text-color": "#345e8c"
    },
    "Char": {
      "text-color": "#2c6f2d",
      "selected-text-color": "#2c6f2d"
    },
    "SpecialChar": {
      "text-color": "#006f5f",
      "selected-text-color": "#006f5f"
    },
    "String": {
      "text-color": "#2c6f2d",
      "selected-text-color": "#2c6f2d"
    },
    "VerbatimString": {
      "text-color": "#2c6f2d",
      "selected-text-color": "#2c6f2d"
    },
    "SpecialString": {
      "text-color": "#006f5f",
      "selected-text-color": "#006f5f"
    },
    "Import": {
      "text-color": "#6e52ab",
      "selected-text-color": "#6e52ab"
    },
    "DataType": {
      "text-color": "#8c3eb2",
      "selected-text-color": "#8c3eb2"
    },
    "DecVal": {
      "text-color": "#815b02",
      "selected-text-color": "#815b02"
    },
    "BaseN": {
      "text-color": "#815b02",
      "selected-text-color": "#815b02"
    },
    "Float": {
      "text-color": "#815b02",
      "selected-text-color": "#815b02"
    },
    "Constant": {
      "text-color": "#3659ca",
      "selected-text-color": "#3659ca"
    },
    "Comment": {
      "text-color": "#58637c",
      "selected-text-color": "#58637c",
      "italic": true
    },
    "Documentation": {
      "text-color": "#58637c",
      "selected-text-color": "#58637c",
      "italic": true
    },
    "Annotation": {
      "text-color": "#345e8c",
      "selected-text-color": "#345e8c"
    },
    "CommentVar": {
      "text-color": "#934b66",
      "selected-text-color": "#934b66"
    },
    "RegionMarker": {
      "text-color": "#6e52ab",
      "selected-text-color": "#6e52ab"
    },
    "Information": {
      "text-color": "#006f5f",
      "selected-text-color": "#006f5f"
    },
    "Warning": {
      "text-color": "#815b02",
      "selected-text-color": "#815b02"
    },
    "Alert": {
      "text-color": "#bb262a",
      "selected-text-color": "#bb262a",
      "bold": true
    },
    "Error": {
      "text-color": "#bb262a",
      "selected-text-color": "#bb262a"
    },
    "Others": {
      "text-color": "#3659ca",
      "selected-text-color": "#3659ca"
    }
  },
  "editor-colors": {
    "BackgroundColor": "#f2f6ff",
    "CodeFolding": "#e9cce3",
    "BracketMatching": "#e4e9f6",
    "CurrentLine": "#e4e9f6",
    "IconBorder": "#e3eafb",
    "IndentationLine": "#b9c1d5",
    "LineNumbers": "#7a859f",
    "CurrentLineNumber": "#b9488b",
    "MarkBookmark": "#006f5f",
    "MarkBreakpointActive": "#bb262a",
    "MarkBreakpointReached": "#815b02",
    "MarkBreakpointDisabled": "#909bb6",
    "MarkExecution": "#7a859f",
    "MarkWarning": "#815b02",
    "MarkError": "#bb262a",
    "ModifiedLines": "#815b02",
    "ReplaceHighlight": "#b9488b",
    "SavedLines": "#2c6f2d",
    "SearchHighlight": "#d5d2ed",
    "TextSelection": "#e9cce3",
    "Separator": "#7a859f",
    "SpellChecking": "#bb262a",
    "TabMarker": "#909bb6",
    "TemplateBackground": "#c9d2e5",
    "TemplatePlaceholder": "#b9c1d5",
    "TemplateFocusedPlaceholder": "#aab3c7",
    "TemplateReadOnlyPlaceholder": "#e3eafb",
    "WordWrapMarker": "#909bb6"
  }
}
