# vim:ft=kitty
## name: Darkberry Wisp
## license: MIT
## blurb: Light. Text is a violet-leaning cousin of the paint colour.

foreground #4f3143
background #fbf4f8
selection_foreground #4f3143
selection_background #f0cadd
cursor #a83570
cursor_text_color #fbf4f8
url_color #026b80
active_border_color #b9488b
inactive_border_color #ac93a2
bell_border_color #815b02
wayland_titlebar_color #f3e6ef
macos_titlebar_color #f3e6ef
active_tab_foreground #fbf4f8
active_tab_background #d21570
inactive_tab_foreground #694e5f
inactive_tab_background #f3e6ef
tab_bar_background #ebdae5
mark1_foreground #fbf4f8
mark1_background #7350a8
mark2_foreground #fbf4f8
mark2_background #8c3eb2
mark3_foreground #fbf4f8
mark3_background #1d64a4

color0 #5a4050
color8 #694e5f
color1 #bb262a
color9 #c5352f
color2 #2c6f2d
color10 #327938
color3 #815b02
color11 #89650e
color4 #3659ca
color12 #4b60d3
color5 #bf0b64
color13 #cb216a
color6 #006f5f
color14 #12796a
color7 #c3abb9
color15 #d0bac8
color16 #a24712
color17 #934b66
