# vim:ft=kitty
## name: Darkberry Blackwater
## license: MIT
## blurb: Darkest. Deeper wine surfaces, same accents as Mire.

foreground #ede1e9
background #1d121a
selection_foreground #ede1e9
selection_background #66394c
cursor #feafd4
cursor_text_color #12090f
url_color #86c0cc
active_border_color #ba4889
inactive_border_color #6b5764
bell_border_color #e8c98a
wayland_titlebar_color #170d13
macos_titlebar_color #170d13
active_tab_foreground #1d121a
active_tab_background #fd7ca5
inactive_tab_foreground #c6b7c0
inactive_tab_background #170d13
tab_bar_background #12090f
mark1_foreground #12090f
mark1_background #baa8dc
mark2_foreground #12090f
mark2_background #ddb0ec
mark3_foreground #12090f
mark3_background #7fb4e0

color0 #34222e
color8 #432c3b
color1 #f06a6a
color9 #ed5858
color2 #a3daa3
color10 #87cf8e
color3 #e8c98a
color11 #dcbb6d
color4 #8fb0f2
color12 #7da4f4
color5 #fd7ca5
color13 #fc6796
color6 #9ed0c4
color14 #7cc7b8
color7 #c6b7c0
color15 #d8cbd4
color16 #f2ad8a
color17 #e7c5d8
