# vim:ft=kitty
## name: Darkberry Mire
## license: MIT
## blurb: The main dark flavour: wine-dark mire with berry accents.

foreground #efe3eb
background #2a1e26
selection_foreground #efe3eb
selection_background #502f3d
cursor #feafd4
cursor_text_color #1c1119
url_color #86c0cc
active_border_color #be4c8d
inactive_border_color #91828b
bell_border_color #e8c98a
wayland_titlebar_color #23161f
macos_titlebar_color #23161f
active_tab_foreground #1c1119
active_tab_background #fd7ca5
inactive_tab_foreground #cbbcc5
inactive_tab_background #23161f
tab_bar_background #1c1119
mark1_foreground #1c1119
mark1_background #baa8dc
mark2_foreground #1c1119
mark2_background #ddb0ec
mark3_foreground #1c1119
mark3_background #7fb4e0

color0 #3e2936
color8 #4f3143
color1 #f06a6a
color9 #ed5858
color2 #a3daa3
color10 #87cf8e
color3 #e8c98a
color11 #dcbb6d
color4 #8fb0f2
color12 #7da4f4
color5 #fd7ca5
color13 #fc6796
color6 #9ed0c4
color14 #7cc7b8
color7 #cbbcc5
color15 #ddd0d9
color16 #f2ad8a
color17 #e7c5d8
