# vim:ft=kitty
## name: Darkberry Fen
## license: MIT
## blurb: Soft dark. The background (#4c3342) is within a shade of the paint colour.

foreground #f2e6ee
background #4f3143
selection_foreground #f2e6ee
selection_background #6e4457
cursor #ffc4dd
cursor_text_color #35212e
url_color #a0d0da
active_border_color #ba4889
inactive_border_color #8f6e82
bell_border_color #f0d6a0
wayland_titlebar_color #402838
macos_titlebar_color #402838
active_tab_foreground #4f3143
active_tab_background #fa99b4
inactive_tab_foreground #ccbac5
inactive_tab_background #402838
tab_bar_background #35212e
mark1_foreground #35212e
mark1_background #cebede
mark2_foreground #35212e
mark2_background #ecbcfc
mark3_foreground #35212e
mark3_background #9cc6ea

color0 #6c4c60
color8 #7b5a6e
color1 #ff8a8a
color9 #fc7776
color2 #b7e6b7
color10 #9bdba1
color3 #f0d6a0
color11 #e3c782
color4 #a4c3f6
color12 #8fb6f7
color5 #fa99b4
color13 #f985a5
color6 #bad9d4
color14 #99cfc8
color7 #ccbac5
color15 #dfced9
color16 #f7bf9e
color17 #eedce5
