# vim:ft=kitty
## name: Darkberry Wisp
## license: MIT
## blurb: Light. Text is a violet-leaning cousin of the paint colour.

foreground #4f3143
background #fbf4f8
selection_foreground #4f3143
selection_background #f4cce0
cursor #b7437d
cursor_text_color #fbf4f8
url_color #1b778c
active_border_color #b9488b
inactive_border_color #ac93a2
bell_border_color #90670a
wayland_titlebar_color #f3e6ef
macos_titlebar_color #f3e6ef
active_tab_foreground #fbf4f8
active_tab_background #d21570
inactive_tab_foreground #694e5f
inactive_tab_background #f3e6ef
tab_bar_background #ebdae5
mark1_foreground #fbf4f8
mark1_background #7a58b0
mark2_foreground #fbf4f8
mark2_background #9a4cc0
mark3_foreground #fbf4f8
mark3_background #2a6fb0

color0 #5a4050
color8 #694e5f
color1 #cc3838
color9 #d8473e
color2 #377a37
color10 #3e8543
color3 #90670a
color11 #997317
color4 #3b5fd0
color12 #5067da
color5 #d21570
color13 #df2a76
color6 #1d7d6c
color14 #298878
color7 #c3abb9
color15 #d0bac8
color16 #b15423
color17 #a15873
