#!/bin/bash
# Blueberry Fen for JankyBorders (the macOS window-border tool used with yabai and AeroSpace). Blueberry tint of Fen: dark, neutrals leaned toward blueberry (base 0xff2f3b58).
#
# Generated by build.mjs from src/ports/borders.sh. Do not edit ports/borders/.
# Install with:  cp blueberry-fen.sh ~/.config/borders/bordersrc
# Then restart borders (brew services restart borders). Running this file while borders
# is already up sends it the new options instead, which is a quick way to try a flavour.
#
# Colours are 0xAARRGGBB. The focused window follows ui.border.active, which is the
# accent; every other window follows ui.border.inactive, which is quiet enough to sit
# beside the tiled gap without drawing the eye. Only the colours are the theme; width,
# style and hidpi are plain defaults, so change them freely.
borders style=round width=6.0 hidpi=on \
  active_color=0xffdc67a7 \
  inactive_color=0xff808daa
